buku_run_jq after merge knatsakis/rofi-buku

diff --git a/buku_run_jq b/buku_run_jq
--- a/buku_run_jq
+++ b/buku_run_jq
@@ -2,6 +2,7 @@
 # https://github.com/carnager/buku_run
 # https://github.com/GandaG/buku_run
 # https://github.com/Cybolic/buku_run !!jq
+# https://github.com/knatsakis/rofi-buku !!
 # https://github.com/davatorium/rofi/issues/1069#issuecomment-599724565
 # rofi_l() {
 #   rofi -dmenu -i -no-levenshtein-sort -width 1000 "$@"
@@ -43,13 +44,13 @@ if [[ -z $XDG_CONFIG_DIR ]]; then
 	if [[ -f $HOME/.config/buku_run/config ]]; then
 		source $HOME/.config/buku_run/config
 	else
-		echo "User config file \'~/.config/buku_run/config\' not found. using global config"
+		echo "User config file '~/.config/buku_run/config' not found. using global config"
 	fi
 else
 	if [[ -f "${XDG_CONFIG_DIR}/buku_run/config" ]]; then
 		source "${XDG_CONFIG_DIR}/buku_run/config"
 	else
-		echo "User config file \'~/.config/buku_run/config\' not found. using global config"
+		echo "User config file '~/.config/buku_run/config' not found. using global config"
 	fi
 fi
 
@@ -60,7 +61,7 @@ Use <span color='${help_color}'>${switch_view}</span> to switch View. <span colo
 		content=$(parseBuku)
 		menu=$(echo "${content}" | _rofi -p '> ' -filter "${filter}" -mesg "${HELP}" -kb-custom-1 "${new_bookmark}" -kb-custom-2 "${switch_view}" -kb-custom-3 "${actions}" -kb-custom-4 "${edit}" -kb-custom-5 "${delete}")
 	elif [[ $mode == "tags" ]]; then
-		menu=$(buku --np --st | awk '{$NF=""; print $0}' | cut -d ' ' -f2- | _rofi -p '> ' -mesg "${HELP}" -kb-custom-1 "${new_bookmark}" -kb-custom-2 "${switch_view}" -kb-custom-3 "${actions}" -kb-custom-4 "${edit}" -kb-custom-5 "${delete}")
+		menu=$(buku --nostdin --np --st | grep -v -e '^waiting for input$' -e '^$' | awk '{$NF=""; print $0}' | cut -d ' ' -f2- | _rofi -p '> ' -mesg "${HELP}" -kb-custom-1 "${new_bookmark}" -kb-custom-2 "${switch_view}" -kb-custom-3 "${actions}" -kb-custom-4 "${edit}" -kb-custom-5 "${delete}")
 	fi
 	val=$?
 	if [[ $val -eq 1 ]]; then
@@ -85,7 +86,7 @@ Use <span color='${help_color}'>${switch_view}</span> to switch View. <span colo
 		if [[ $mode == "bookmarks" ]]; then
 			id=$(getId "$content" "$menu")
 			for bm in ${id}; do
-				buku -o "${bm}"
+				buku --nostdin -o "${bm}"
 			done
 		elif [[ $mode == "tags" ]]; then
 			filter="${menu}" mode="bookmarks" main
@@ -95,7 +96,7 @@ Use <span color='${help_color}'>${switch_view}</span> to switch View. <span colo
 
 optionsMenu() {
 	if [[ $mode == "bookmarks" ]]; then
-		askmenu=$(echo -e "< Return\n---\n1. Edit\n2. Delete" | _rofi -p '> ' -mesg "Choose Action for bookmark")
+		askmenu=$(echo -e "< Return\\n---\\n1. Edit\\n2. Delete" | _rofi -p '> ' -mesg "Choose Action for bookmark")
 		val=$?
 		if [[ $val -eq 1 ]]; then
 			exit
@@ -110,7 +111,7 @@ optionsMenu() {
 			fi
 		fi
 	elif [[ $mode == "tags" ]]; then
-		askmenu=$(echo -e "< Return\n---\n1. Replace Tag\n2. Delete Tag" | _rofi -p '> ' -mesg "Choose Action for tag \"${menu}\"")
+		askmenu=$(echo -e "< Return\\n---\\n1. Replace Tag\\n2. Delete Tag" | _rofi -p '> ' -mesg "Choose Action for tag \"${menu}\"")
 		val=$?
 		if [[ $val -eq 1 ]]; then
 			exit
@@ -127,18 +128,19 @@ optionsMenu() {
 					if [[ $newtag == "" ]]; then
 						mode=tags main
 					else
-						buku -r "${menu}" "${newtag}"
+						buku --nostdin -replace "${menu}" "${newtag}"
 						mode=tags main
 					fi
 				fi
 			elif [[ $askmenu == "2. Delete Tag" ]]; then
-				delask=$(echo -e "1. Yes\n2. No" | _rofi -p '> ' -mesg "Really delete tag?")
+				delask=$(echo -e "1. Yes\\n2. No" | _rofi -p '> ' -mesg "Really delete tag \"${menu}\" from ALL bookmarks?")
 				val=$?
 				if [[ $val -eq 1 ]]; then
 					exit
 				elif [[ $val -eq 0 ]]; then
 					if [[ $delask == "1. Yes" ]]; then
-						buku -r "${menu}"
+						# buku --nostdin -r "${menu}"
+						echo y | script -qfc "buku --nostdin --replace ${menu}" /dev/null
 						mode=tags main
 					elif [[ $delask == "2. No" ]]; then
 						mode=tags main
@@ -151,7 +153,7 @@ optionsMenu() {
 
 deleteMenu() {
 	id=$(getId "$content" "$menu")
-	delask=$(echo -e "1. Yes\n2. No" | _rofi -p '> ' -mesg "Really delete bookmark?")
+	delask=$(echo -e "1. Yes\\n2. No" | _rofi -p '> ' -mesg "Really delete bookmark?")
 	val=$?
 	if [[ $val -eq 1 ]]; then
 		exit
@@ -167,54 +169,33 @@ deleteMenu() {
 
 editMenu() {
 	id=$(getId "$content" "$menu")
-	title="$(getTitleFromId $id)"
-	bookmark="$(getUrlFromId $id)"
-	tags="$(getTagsFromId $id)"
-	content=$(echo -e "1. title: $title\n2. url: $bookmark\n3. tags: $tags")
-	editmenu=$(echo -e "< Return\n---\n${content}" | _rofi -p '> ')
+
+	title="$(getTitleFromId "${id}")"
+	url="$(getUrlFromId "${id}")"
+	comment="$(getCommentFromId "${id}")"
+	tags="$(getTagsFromId "${id}")"
+
+	content="1. Title: $title\\n2. URL: $url\\n3. Comment: $comment\\n4. Tags: $tags"
+	editmenu=$(echo -e "< Return\\n---\\n${content}" | _rofi -p '> ')
 	val=$?
+
 	if [[ $val -eq 1 ]]; then
 		exit
 	elif [[ $val -eq 0 ]]; then
 		if [[ $editmenu == "< Return" ]]; then
 			main
-		elif [[ $editmenu == "tags: NOTAG" ]]; then
-			addTags --update
-		elif [[ $editmenu =~ tags:* ]]; then
-			tags="${tags}" editTags
-		elif [[ $editmenu =~ url:* ]]; then
-			editBookmark
-		elif [[ $editmenu =~ title:* ]]; then
+		elif [[ $editmenu =~ Title:* ]]; then
 			editTitle
+		elif [[ $editmenu =~ URL:* ]]; then
+			editUrl
+		elif [[ $editmenu =~ Comment:* ]]; then
+			editComment
+		elif [[ $editmenu == "Tags: NOTAG" ]]; then
+			addTags --update
+		elif [[ $editmenu =~ Tags:* ]]; then
+			tags="${tags}" editTags
 		fi
 	fi
-}
-
-editTags() {
-	edittagsmenu=$(echo | _rofi -filter "${tags}" -p '> ' -mesg "Edit Tags and hit Enter")
-	val=$?
-	if [[ $val -eq 1 ]]; then
-		exit
-	elif [[ $val -eq 0 ]]; then
-		buku -u ${id} --tag "${edittagsmenu}"
-	fi
-	mode=bookmarks main
-}
-
-editBookmark() {
-	bmarkmenu=$(echo "" | _rofi -p "> " -filter "${bookmark}" -mesg "Edit Bookmark and hit Enter")
-	val=$?
-	if [[ $val -eq 1 ]]; then
-		exit
-	elif [[ $val -eq 0 ]]; then
-		if [[ $bmarkmenu == "http"* ]]; then
-			buku -u "${id}" --url "${bmarkmenu}"
-		else
-			echo "" | _rofi -e "Not a valid URI, Make sure URLs start with http"
-			editBookmark
-		fi
-	fi
-	mode=bookmarks main
 }
 
 editTitle() {
@@ -223,7 +204,47 @@ editTitle() {
 	if [[ $val -eq 1 ]]; then
 		exit
 	elif [[ $val -eq 0 ]]; then
-		buku -u "${id}" --title "${titlemenu}"
+		buku --nostdin -u "${id}" --title "${titlemenu}"
+	fi
+	mode=bookmarks main
+}
+
+editUrl() {
+	urlmenu=$(echo "" | _rofi -p "> " -filter "${url}" -mesg "Edit URL and hit Enter")
+	val=$?
+	if [[ $val -eq 1 ]]; then
+		exit
+	elif [[ $val -eq 0 ]]; then
+		if [[ $urlmenu == "http"* ]]; then
+			buku --nostdin -u "${id}" --url "${urlmenu}"
+		else
+			echo "" | _rofi -e "Not a valid URI, Make sure URLs start with http"
+			editUrl
+		fi
+	fi
+	mode=bookmarks main
+}
+
+editComment() {
+	commentmenu=$(echo "" | _rofi -p "> " -filter "${comment}" -mesg "Edit Comment and hit Enter")
+	val=$?
+
+	if [[ $val -eq 1 ]]; then
+		exit
+	elif [[ $val -eq 0 ]]; then
+		buku --nostdin -u "${id}" --comment "${commentmenu}"
+	fi
+
+	mode=bookmarks main
+}
+
+editTags() {
+	edittagsmenu=$(echo | _rofi -filter "${tags}" -p '> ' -mesg "Edit Tags and hit Enter")
+	val=$?
+	if [[ $val -eq 1 ]]; then
+		exit
+	elif [[ $val -eq 0 ]]; then
+		buku --nostdin -u "${id}" --tag "${edittagsmenu}"
 	fi
 	mode=bookmarks main
 }
@@ -240,7 +261,7 @@ addMark() {
 }
 
 addTags() {
-	inserttags=$(buku --np --st | awk '{$NF=""; print $0}' | cut -d ' ' -f2- | _rofi -p '> ' -mesg "Add some tags. Separate tags with ', '")
+	inserttags=$(buku --nostdin --np --st | grep -v '^waiting for input$' | awk '{$NF=""; print $0}' | cut -d ' ' -f2- | _rofi -p '> ' -mesg "Add some tags. Separate tags with ', '")
 	val=$?
 	if [[ $val -eq 1 ]]; then
 		exit
@@ -255,9 +276,9 @@ addTags() {
 			tags=${inserttags}
 		fi
 		if [[ $1 == "--update" ]]; then
-			buku -u "${id}" --tag ${tags}
+			buku --nostdin -u "${id}" --tag "${tags}"
 		else
-			buku -a ${inserturl} ${tags}
+			buku --nostdin -a "${inserturl}" "${tags}"
 		fi
 	fi
 }
@@ -271,21 +292,21 @@ parseBuku() {
 	elif [ "$display_type" = "5" ]; then
 		jq_program='.[] | (.index | tostring) + " " + .title[0:'$max_str_width'] + "\r " + .uri[0:'$max_str_width'] + "\r " + .tags'
 	fi
-	content="$(buku --nc --np --nostdin --print --json)"
+	content="$(buku --nostdin --nc --np --nostdin --print --json)"
 	if [[ "$content" = 'buku: waiting'* ]]; then
 		content="$(echo "$content" | tail -n+2)"
 	fi
-	echo "$(echo "$content" | jq --raw-output "$jq_program" | column -t -s $'\t')"
+	echo "$content" | jq --raw-output "$jq_program" | column -t -s $'\t'
 }
 
 getId() {
-	id=$(echo "${2%% *}")
+	id="${2%% *}"
 	if [ -z "$id" ]; then
 		prev=""
 		IFS=$'\n'
 		for line in $1; do
 			if [ "$2" = "$line" ]; then
-				id=$(echo "${prev%% *}")
+				id="${prev%% *}"
 				break
 			else
 				prev="$line"
@@ -296,15 +317,19 @@ getId() {
 }
 
 getTitleFromId() {
-	echo "$(buku --nc --np --print $1 --json | jq --raw-output '.title')"
+	buku --nostdin --nc --np --print "${1}" --json | jq --raw-output '.title'
 }
 
 getUrlFromId() {
-	echo "$(buku --nc --np --print $1 --json | jq --raw-output '.uri')"
+	buku --nostdin --nc --np --print "${1}" --json | jq --raw-output '.uri'
+}
+
+getCommentFromId() {
+	buku --nostdin --nc --np --print "${1}" --json | jq --raw-output '.description'
 }
 
 getTagsFromId() {
-	echo "$(buku --nc --np --print $1 --json | jq --raw-output '.tags')"
+	buku --nostdin --nc --np --print "${1}" --json | jq --raw-output '.tags'
 }
 
 if [[ $1 == "add" ]]; then
